# Header
nav:
  About: /about
  Case Studies: /case-studies
  Hire Me: /work
rss: /atom.xml

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
